### ISSUE TITLE
wiki: expose the wiki as a git branch

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#1]
Wiki of this project contains important documentation. It is a git repository, but only accessible to project members.
It would be nice to expose the wiki as a branch in the main repository, so that others can send pull requests to wiki pages.
See [Enabling pull requests on GitHub wikis](https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html) for how to setup.

**Comment by Zhiyi-Zhang** [comment]
Thanks for the helpful link.

**Comment by Zhiyi-Zhang** [comment]
New repo is here: https://github.com/named-data-iot/ndn-lite-wiki
wiki page footer also added.
