### ISSUE TITLE
Clarify required C version

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#12]
README says:

> The library is written in standard C.

C language has multiple versions, including C89, C95, C99, C11, C17.
It’s necessary to declare the minimal C version this library should support, so that contributions do not use features not supported by that version.

**Comment by Zhiyi-Zhang** [comment]
I think C11 should be a good fit given today's wide adoption of C11.
We also plan to use the atomic int support from C11.

**Comment by zjkmxy** [comment]
> I think C11 should be a good fit given today's wide adoption of C11.
> We also plan to use the atomic int support from C11.

C11 has been supported by llvm clang, gcc and intel-cc for several versions.
Microsoft's compiler seems not to support but I don't think we need to support Win10-IoT.
So I agree with C11.

**Comment by yoursunny** [comment]
This information should be added to `README.md`, and then this issue can close.

**Comment by Zhiyi-Zhang** [comment]
Thank you for your help.
