### ISSUE TITLE
security: decouple ECDSA signing and input digesting

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#14]
As of a4dcb80458dff521ac8767b0e0067c1e14fab98d, `ndn_lite_default_ecdsa_sign` internally computes a SHA256 digest of the input data before creating a signature over the digest.
However, digesting and signing are two different operations and they should be decoupled. The ECC backend should not perform digesting. Instead, the frontend could invoke the SHA256 backend to compute the digest, then invoke ECC backend to sign the digest.

**Comment by Zhiyi-Zhang** [comment]
I think this has already been solved.
