### ISSUE TITLE
security: hardware key abstraction

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#2]
Currently (commit 219d5a64db6f39446ae6431f93584d19e88b7766), security backend APIs assume that HMAC and ECC keys are available in the RAM and accessible by the main application. With the rise of hardware crypto element such as [ATSHA204A](https://www.microchip.com/wwwproducts/en/ATsha204a) and [ATECC508A](https://www.microchip.com/wwwproducts/en/ATECC508A), this assumption is no longer true.
When using a hardware crypto element, the main application can command a peripheral to generate a key (or key pair), and use that key to perform signing, verification, ECDH, and other operations. The HMAC key or ECC private key can be referenced by a "handle" or "slot number", but can never be read into RAM.

To support hardware crypto element, ndn-lite should have a key abstraction:
1. Every key is represented by an opaque *abstract\_key* struct implemented by the backend.
2. In most cases, the backend can provide a function to load in-memory key bits into an *abstract\_key*.
3. Signing, verification, and ECDH functions should accept *abstract\_key* pointer instead of key bits.
4. Key generation function should return/fill *abstract\_key* struct instead of returning key bits.
5. In most cases, the backend can provide a function to read public key out of an *abstract\_key*.
6. There is also a function to read private key out of an *abstract\_key*, but this function won't work with many crypto element peripherals.

**Comment by Zhiyi-Zhang** [comment]
The current commit (a4dcb80458dff521ac8767b0e0067c1e14fab98d) and its previous four commits addressed your issue.
