### ISSUE TITLE
Declare LICENSE

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#22]
It’s necessary to declare what license this work is released under, so that other projects can adopt this library.

**Comment by Pesa** [comment]
Most (all?) source files contain the following prologue:
```
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
```

A separate `LICENSE` file is not technically required but is considered good practice (and the above comment refers to it).

**Comment by Zhiyi-Zhang** [comment]
Let's use LGPLv3. I already added the LICENSE and updated all the boilerplates in source/header files.
