### ISSUE TITLE
Unusable FreshnessPeriod

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#26]
Type `ndn_metainfo_t` has field:

    uint8_t freshness_period[4];

This declaration is difficult to use in applications.
*FreshnessPeriod* element should be an integer, not a byte array.

Although setter function `ndn_metainfo_set_freshness_period` exists, there isn't a getter function, so that application needs to directly access the field.

**Comment by RoySCU** [comment]
Commit c44723f6fb2e11de4cd56539aed4a2751365f1e4 will address this problem. `ndn_metainfo_t` now uses `uint32_t` for `freshness_period`. Thank you for pointing this out.
