### ISSUE TITLE
Incorrect decoding of InterestLifetime

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#29]
As of c03b56040b320de6c47ee32c5303d9b1bf8841a0, `ndn_interest_from_block` invokes:

    while (decoder.offset < block_size) {
      decoder_get_type(&decoder, &type);
      uint32_t length = 0;
      if (type == TLV_InterestLifetime) {
        decoder_get_length(&decoder, &length);
        decoder_get_uint16_value(&decoder, &interest->lifetime);
      }
    }

It assumes *InterestLifetime* has TLV-LENGTH=2 without checking it.
NDN Packet Format v0.3 specifies that *InterestLifetime* element is NonNegativeInteger that could have 1, 2, 4, or 8 octets.
Consequently, given input:

    05xx
      0703080141
      0C0400012100

the decoding function would incorrectly read *InterestLifetime* to be 1, and erroneously interpret `2100` as *CanBePrefix*.

**Comment by RoySCU** [comment]
Commit a5a0b72ba457e46b24ffe3b3e04a2d7b6c4c7e0d will address this problem. For some reasons NDN-Lite now decides to accept 4 octets _InterestLifetime_, rather than all four options. Can you @Zhiyi-Zhang explain a bit about that? 😃

**Comment by Zhiyi-Zhang** [comment]
Commit b180d1586db5b6259aaf1a16068ac3edc94c5907 fixed the issue.
