### ISSUE TITLE
Follow the new signed interest format

### ISSUE THREAD

**Issue by Zhiyi-Zhang** [named-data-iot/ndn-lite#32]
Currently, the signed interest format is not approved by NDN format v0.3. After the commit https://gerrit.named-data.net/c/NDN-TLV/+/4942 is merged, the implementation of `encode/signed-interest` should reflect the new format.

**Comment by yoursunny** [comment]
Signed Interest in v0.3 requires signature over non-contiguous buffers. It depends on both #36 and #14 for efficient signing implementation.

**Comment by Zhiyi-Zhang** [comment]
Commit 99374342fc676440da9cc81e25845a934cbeabe5 has addressed the issue. Both #36 and #14 were closed also.
