### ISSUE TITLE
Incorrect decoding of FreshnessPeriod

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#33]
As of 5b43c5f59eb19d717ab759d1c7c8fcfcaa329b8c, `ndn_metainfo_tlv_decode` invokes:

    else if (probe == TLV_FreshnessPeriod) {
      decoder_get_length(decoder, &probe);
      decoder_get_uint32_value(decoder, &meta->freshness_period);
      meta->enable_FreshnessPeriod = 1;
    }

It assumes *FreshnessPeriod* has TLV-LENGTH=4 without checking it.
NDN Packet Format v0.3 specifies that *FreshnessPeriod* element is NonNegativeInteger that could have 1, 2, 4, or 8 octets.
Consequently, the decoding function would read *FreshnessPeriod* incorrectly if its TLV-LENGTH is not 4.

**Comment by RoySCU** [comment]
Commit 2ea899bd4c9f5c5034dc89709258678862acbc6b will address this problem. new _FreshnessPeriod_ is encoded/decoded in the same way as _InterestLifetime_ in issue #29. Thank you for pointing this out.
