### ISSUE TITLE
Support incremental SHA256 computation in NDN-Lite security

### ISSUE THREAD

**Issue by Zhiyi-Zhang** [named-data-iot/ndn-lite#36]
To better support the digest computation in NDN Packet encoding/decoding, the security frontend should support SHA256 computation in an incremental manner.
Specifically, the frontend should support functions:
```
ndn_sha256_init
ndn_sha256_update
ndn_sha256_finish
```
And we implement the current `ndn_sha256` with the abovementioned three functions without invoking the backend impl.

**Comment by RoySCU** [comment]
New SHA256 frontend and backend has been updated. NDN-Lite now supports incremental SHA256 computation.
