### ISSUE TITLE
face: add RIOT gnrc support

### ISSUE THREAD

**Issue by RoySCU** [named-data-iot/ndn-lite#39]
RIOT provides a uniform network interface, called GNRC, for most of their devices (includes "native" port on the machine). We have't supported yet. Supporting this will help us develop and test application over RIOT, instead of only porting Unit Tests to it.

**Comment by Zhiyi-Zhang** [comment]
Yes, we need this feature a lot.

**Comment by RoySCU** [comment]
[This Repo](https://github.com/named-data-iot/ndn-lite-over-riot) provides initial RIOT network stack adaptation, as well as their timer.
