### ISSUE TITLE
The original paper of Sign-on-Protocol is not available.

### ISSUE THREAD

**Issue by Paul-HIT** [named-data-iot/ndn-lite#43]
The original paper of Sign-on-Protocol is not available. Where / How can I find it ?

**Comment by peurpdapeurp** [comment]
We are actually still in the process of submitting the paper, so unfortunately we cannot give you a copy to read. However, the submission deadline is by this weekend, so we should be able to either give you a link to the final version of the paper or write a technical report to sum up the protocol for you soon.

**Comment by Paul-HIT** [comment]
Thanks
