### ISSUE TITLE
whether NDN-lite provides the function of encrypting interest

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-lite#46]
Hello,
I'm not sure whether NDN-lite provides the function of encrypting interest,I watched code of the board and didn't find any encryption on interests sent out.Can you tell me some details?Thank you so much.

**Comment by RoySCU** [comment]
Generally speaking, if you want to carry encrypted information in an Interest, you can do it by encrypting Interest Parameters. The APIs are simply missing there, but they should have similar interfaces as Data Content Encryption .
