### ISSUE TITLE
AES input padding is missing

### ISSUE THREAD

**Issue by Zhiyi-Zhang** [named-data-iot/ndn-lite#47]
Current NDN-Lite backend is using Tinycrypt to do AES encryption. However, Tinycrypt does not provide padding when the input plaintext length % 16 != 0, and lead to errors when using AES APIs.
To fix this problem, we need to provide padding function by ourselves.
Let's use PKCS#7 padding for AES, that is, pad the last block with n bytes all with value n.

**Comment by RoySCU** [comment]
After commit 0d5ac00df1afaf0e1781c18c887e3e417293e3eb, we now support PKCS#7 padding.
