### ISSUE TITLE
Modify bootstrapping implementation to use NDN packets

### ISSUE THREAD

**Issue by peurpdapeurp** [named-data-iot/ndn-lite#49]

**Comment by Zhiyi-Zhang** [comment]
This issue has been addressed by app-support/security-bootstrapping.c/.h

**Comment by yoursunny** [comment]
`app-support/secure-sign-on` could be deleted.

**Comment by yoursunny** [comment]
ce6ab3a845f65bbb495a6d2127c37095bbc68cd7 deletes `app-support/secure-sign-on`. This issue should be closed.
P.S. the commit message could have included `fixes #49` to auto-close this issue upon merging.

**Comment by Zhiyi-Zhang** [comment]
app-support/secure-sign-on has been deleted.
