### ISSUE TITLE
Use micro-ecc 'static' branch

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#57]
[micro-ecc library](https://github.com/kmackay/micro-ecc) used in security-backend has two variants:
* [master branch](https://github.com/kmackay/micro-ecc/tree/master) allows choosing a curve at runtime.
* [static branch](https://github.com/kmackay/micro-ecc/tree/static) requires choosing a curve at compile time.

The 'static' branch has smaller binary code size, lower memory usage, and faster execution.

In typical IoT use case, it's rarely necessary to support multiple ECC curves. Therefore, NDN-Lite should switch to micro-ecc 'static' branch, and statically select *secp256r1* curve that is the default setting in other libraries including ndn-cxx and PyNDN.

**Comment by RoySCU** [comment]
Hi Junxiao, I think I'm still little unclear about this. Which one you are suggesting?

- Using _secp256r1_ (with micro-ecc 'static' branch) in default security-backend **while remaining** security-frontend interfaces supporting multiple curves (and not work with default backend).
- Using _secp256r1_ exclusively in NDN-Lite **(no choice at all)**.

**Comment by RoySCU** [comment]
I just reviewed security backend. Current NDN-Lite includes two libraries micro-ecc and [tinycrypt](https://github.com/intel/tinycrypt). Tinycrypt has all functions micro-ecc has but only use _p256_ curve in ECC operation, and that's why we also use micro-ecc. Given that, I wonder if we can use tinycrypt only and remove micro-ecc entirely (if possible). This can be reserved for future.

**Comment by RoySCU** [comment]
> TinyCrypt lacks ECC key generation feature.

It seems TinyCrypt has [ECC key generation](https://github.com/intel/tinycrypt/blob/master/lib/include/tinycrypt/ecc_dh.h#L78-L94) function? 

> Its ECC code is partially a copy of micro-ecc static branch

Yes, they claim in documentation that their ECC implementation is based on micro-ecc and their APIs look alike also, thus easy to switch to. 

Nevertheless, NDN-Lite should first switch to micro-ecc 'static', then consider the usage of TinyCrypt?

**Comment by RoySCU** [comment]
@Zhiyi-Zhang Hi Zhiyi, I wonder your opinions here?
