### ISSUE TITLE
Question/feature request: Expose forwarder for easier debugging.

### ISSUE THREAD

**Issue by yan-foto** [named-data-iot/ndn-lite#76]
Hi everyone! @Pairarma and I, are testing integration of changes in #74 for RIOT (see [my fork](https://github.com/yan-foto/RIOT/tree/feature/ndn-lite/pkg/ndn-lite)). 

We were wondering if there are any explicit reasons not to give users access to the [`forwarder`](https://github.com/named-data-iot/ndn-lite/blob/master/forwarder/forwarder.c#L58), mainly to be able to list fib, pit, and face entries. The current implementation allows adding faces, routes, etc. but does not allow listing them which makes debugging a real pain.

If you guys are OK with it, I can send a PR with a single function which returns a const pointer to `forwarder` struct.

**Comment by Zhiyi-Zhang** [comment]
The reason is for hiding the details of underlying forwarding details.
I think it's fine to have that function and yeah a PR sounds good.
