### ISSUE TITLE
ps_publish_content invalid array index

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#77]
https://github.com/named-data-iot/ndn-lite/blob/d60a114a4c4e8422577ab8ae3817f79eed948254/app-support/pub-sub.c#L587-L596

In this code, if `pub_topics[0]` happens to be the oldest pub topic, `index` will remain `-1` and `topic` will be pointing to `pub_topics[-1]` that is an invalid position.

**Comment by tianyuan129** [comment]
9291110 addressed in `develop` branch.
