### ISSUE TITLE
Activate continuous integration in default branch

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#80]
Currently, Travis CI is enabled in `develop` branch only, and not activated in the default branch.
This means, some incoming code targeting the default branch is not being CI-tested.

It is necessary to have CI testing, including unit tests, in the default branch.

**Comment by yoursunny** [comment]
Due to this issue, my recent bug reports are based on reviews on the `develop` branch, not the default branch.
Likewise, I'll expect the bug fixes targeting `develop` or another CI-tested branch.

**Comment by yan-foto** [comment]
It was an unfortunate move to have multiple changes (CI integration included) in a single PR. If you guys have any quick tests at hand that can verify my changes in #74 so it can be merged to master? It would also bring CI to the master :)

**Comment by tianyuan129** [comment]
after 6eb47ecca595ad9dc27d5000ff6fa64e975de17a, CI was now brought to master.

**Comment by yoursunny** [comment]
Travis CI badge in README should not explicitly link to `master`, because it's impractical to change the badge for each branch. Instead, leave off the branch and let it point to the latest build.

**Comment by tianyuan129** [comment]
3faf4f2
