### ISSUE TITLE
Opt-in to hacktoberfest

### ISSUE THREAD

**Issue by yoursunny** [named-data-iot/ndn-lite#84]
I'd like to contribute to this repository as part of Hacktoberfest. Some issues I may address are #35 #55 #78.
In order for the Pull Requests to count toward my Hacktoberfest contributions, it is necessary for the maintainer to add `hacktoberfest` as a repository topic. Can you do that?
https://github.com/digitalocean/hacktoberfest/pull/596

**Comment by tianyuan129** [comment]
done.
